seleniumhub:
  image: selenium/hub
  ports:
    - "4444:4444"
firefox:
  image: selenium/node-firefox-debug
  ports: 
    - 4577
  links:
    - seleniumhub:hub
chrome:
  image: selenium/node-chrome-debug
  ports: 
    - 4578
  links:
    - seleniumhub:hub

